<script setup>
import Modal from "@/Components/Modal.vue";

const emit = defineEmits(["close"]);

const props = defineProps({
    show: Boolean,

});
</script>

<template>
  <div class="relative overflow-hidden bg-white">
    <div class="mx-auto max-w-7xl">
        <Modal :show="props.show" @close="emit('close')">
            <div class="p-6">
                        
                <h2 style="text-align:justify">GİZLİLİK POLİTİKAMIZ</h2>

                <p style="text-align:justify">Metropol International i&ccedil;in kişisel bilgilerinizi korumanın &ccedil;ok &ouml;nemli olduğunu ve bunların gizliliğine saygı duyduğumuzu bilmenizi istiyoruz. Bu Gizlilik Politikasını, bizimle paylaştığınız kişisel bilgilerinizi nasıl kullandığımızı ve koruduğumuzu a&ccedil;ıklamak i&ccedil;in hazırladık. Bu Politika mibordro.com (&ldquo;Site&rdquo;) ve hizmetlerimizi kullanan, ayrıca hizmet satın alan t&uuml;m kullanıcılar ile bize verilen t&uuml;m bilgiler i&ccedil;in ge&ccedil;erlidir. Hizmet satın almak suretiyle, Gizlilik Beyanı h&uuml;k&uuml;mlerini okuduğunuzu, incelediğinizi ve i&ccedil;eriğini aynen kabul etmiş sayılacağınızı &ouml;nemle belirtiriz. Web sitemizi ve hizmetlerimizi kullanmak ve/veya hizmet satın almak suretiyle işbu Gizlilik Politikasında belirtilen uygulamaları ve kuralları kabul etmektesiniz.</p>

                <p style="text-align:justify">Metropol International gizlilik konusunda T&uuml;rkiye&rsquo;deki yasal d&uuml;zenlemelere uymaktadır. Metropol International, bu web sitesinin diğer &uuml;lkelerin yasalarına tabi olduğu ya da bunlara uygun olarak işletildiği ya da bu web sitesinin herhangi bir kısmının herhangi bir yetkili yargı b&ouml;lgesinde kullanımı i&ccedil;in uygun ya da hazır olduğu hususunda bir taahh&uuml;tte bulunmamaktadır. Web sitemizi kullanmayı se&ccedil;enler, bunu kendi inisiyatifleri doğrultusunda riskleri kendilerine ait olarak yapmaktadır ve t&uuml;m yerel kanunlar, kural ve d&uuml;zenlemelere uymakla y&uuml;k&uuml;ml&uuml;d&uuml;rler. Bu web sitesini kullanan T&uuml;rkiye dışından ziyaret&ccedil;iler, işbu sitenin T&uuml;rkiye Cumhuriyeti kanun ve d&uuml;zenlemelerine tabi olduğunu kabul etmekte ve kendi ulusal yasaları kapsamında ortaya &ccedil;ıkacak t&uuml;m taleplerinden feragat etmektedirler.&nbsp;</p>

                <p style="text-align:justify">Metropol International, işbu Gizlilik Politikasının h&uuml;k&uuml;mlerini mevzuat kapsamında değiştirme, &uuml;zerinde değişiklik, ekleme ya da &ccedil;ıkarma yapma hakkını saklı tutar. İşbu Gizlilik Politikasında yapılan değişiklikler yine bu web sitesinde yayınlanacaktır. Gizlilik politikamızın en g&uuml;ncel halinden haberdar olmaya devam etmek i&ccedil;in zaman zaman web sitemizi kontrol etmenizi &ouml;neririz. Bu sayfanın &uuml;zerindeki &ldquo;Son G&uuml;ncelleme&rdquo; tarihine bakarak sitemizi son ziyaretinizden beri Gizlilik Politikasının revize edilip edilmediğini anlayabilirsiniz. L&uuml;tfen bu Gizlilik Politikasını dikkatle okuyun. Sitemizi kullanmanız ve/veya hizmet satın almanız, herhangi bir sınırlandırma, uygunluk ya da değişiklik olmaksızın işbu Gizlilik Politikasına bağlı olmayı kabul etmeniz anlamına gelmektedir. Herhangi bir zamanda, buradaki t&uuml;m h&uuml;k&uuml;m ve koşulları kabul etmediğiniz takdirde, bu sitenin kullanımına derhal son vermeniz gerekmektedir.</p>

                <h3 style="text-align:justify"><strong>1. Hangi Bilgileri Topluyoruz</strong></h3>

                <p style="text-align:justify">Web sitemiz aracılığıyla iki &ccedil;eşit bilgi topluyoruz: &ldquo;Kişisel Bilgiler&rdquo; (ya da &ldquo;PII&rdquo;) ve &ldquo;Kişisel Olmayan Bilgiler&rdquo; (ya da &ldquo;PII-Olmayan Bilgiler&rdquo;). Kişisel Bilgiler, sizi bir birey olarak tanımlayan ya da tanımlayabilen bilgilerdir (ikamet adresi, telefon numarası ya da fatura bilgileri gibi) ve Kişisel Olmayan Bilgiler ise toptan bilgiler, demografik bilgiler, IP adresleri ve doğrudan kimliğinizi ortaya &ccedil;ıkarmayan diğer bilgilerdir.</p>

                <p style="text-align:justify"><strong>a. Kişisel Olmayan Bilgiler:</strong>&nbsp;Sitemizi ziyaret ettiğinizde veya sitemizle etkileşime ge&ccedil;tiğinizde Metropol International ve Metropol International&rsquo;e hizmet sağlamak i&ccedil;in Metropol International&rsquo;in s&ouml;zleşme yaptığı &uuml;&ccedil;&uuml;nc&uuml; kişiler Kişisel Olmayan Bilgilerinizi (&ouml;rneğin, ziyaret ettiğiniz Site sayfalarının bir katalogunu) toplayabilir. Kişisel Olmayan Bilgiler, anonim ve sizi kişisel olarak tanımlamayan bilgilerdir. Kişisel Olmayan Bilgiler genellikle Sitemiz vasıtasıyla d&ouml;rt farklı kaynaktan toplanır: Internet protokol adresleri ve web logları; &ccedil;erezler (cookies), piksel etiketleri ve diğer benzeri teknolojiler; ve aşağıda a&ccedil;ıklanan şekilde sizin isteyerek verdiğiniz diğer Kişisel Olmayan Bilgiler.</p>

                <p style="text-align:justify"><strong>i. IP Protokol Adresleri ve Web Logoları:</strong>&nbsp;IP adresinizi sunucularımızdaki problemleri teşhis etmek, web sitemizi y&ouml;netmek, site/uygulama ile bağlantınızı en hızlı şekilde sağlayacak veri servisine ulaşmanızı temin etmek ve tercihiniz doğrultusunda ziyaretlerinizde kullanılan dil ve Site&#39;ye erişilen b&ouml;lge a&ccedil;ısından kişiselleştirilmiş bir deneyim sunmak i&ccedil;in alıyor ve saklıyoruz. Sitemizin web sunucuları otomatik olarak, ziyaret&ccedil;ilerin Internet Protokol (IP) adreslerini ve log dosyalarını toplar. IP adresiniz, Internet Servis Sağlayıcınız (ISP) tarafından bilgisayarınıza otomatik olarak tayin edilen bir kimlik numarasıdır. Numara, siz Siteyi ziyaret ettiğinizde ziyaret(ler)inizin zamanı ve ziyaret ettiğiniz sayfa(lar) ile birlikte sunucu log dosyalarımızda otomatik olarak tanımlanır ve saklanır. Bu bilgiler, genel olarak toplanır ve herhangi bir Kişisel Bilgi i&ccedil;ermez.<br />
                IP adresinizi ve t&uuml;m kullanıcıların IP adreslerini sadece Site kullanım d&uuml;zeylerini hesaplama, Site sunucularının problemlerini teşhis etme ve Siteyi idare etme gibi ama&ccedil;larla kullanırız. IP adreslerini toplamak internette standart bir uygulamadır ve bir&ccedil;ok web sitesi tarafından otomatik olarak yapılır. Yukarıda tanımlanan IP adreslerinin Kişisel Olmayan kullanımına ilave olarak, dolandırıcılık ve benzeri su&ccedil;ları &ouml;nlemek amacıyla Kişisel Bilgilerinizle IP adresinizi birbiriyle ilişkilendirebiliriz.&nbsp;</p>

                <p style="text-align:justify"><strong>ii. &Ccedil;erezler (Cookies):</strong>&nbsp;Bizler ve &uuml;&ccedil;&uuml;nc&uuml; kişi hizmet sağlayıcıları, sitemizi nasıl kullandığınız hakkında bilgi toplamak i&ccedil;in &ldquo;&ccedil;erez&rdquo; denilen standart bir teknolojiyi kullanabilir. &Ccedil;erezler bilgisayarınızda kalır ve sitemizin bilinen ziyaret&ccedil;isi olarak bilgisayarınızın tarayıcısını tanımasına yardım eder. &Ouml;rneğin Metropol International hesabınıza girdiğinizde e-posta adresinizi ve isminizi kaydetmek i&ccedil;in &ccedil;erezler kullanılacaktır. B&ouml;ylece aynı bilgisayardan bir dahaki ziyaretinizde, işleminizi hızlandırmak ve daha basit kılmak i&ccedil;in isim ve e-posta adresinizi &ldquo;hatırlayacağız&rdquo;. Zaman zaman, sitemizi idare etmemize yardım eden &ldquo;oturum &ccedil;erezi&rdquo; de kurulabilir. Oturum &ccedil;erezi siz browserınızı kapattığınızda sona erer ve sona erdikten sonra da sizin hakkınızda herhangi bir bilgi tutmaz. &Ccedil;erezlerin kullanımıyla bilgilerin toplanmasını istemiyorsanız &ccedil;erezlere ilişkin se&ccedil;imleri size sunması i&ccedil;in browser tercihlerinizi değiştirmelisiniz. &Ccedil;erezleri reddetmeyi se&ccedil;erseniz, sitemizin belli hizmetlerini (&ouml;rn. siteye giriş yapmanızı gerektiren hizmetler) kullanamayabilirsiniz. &Ccedil;erezler ile toplanan kişisel veriler s&ouml;z konusu olduğu takdirde, Kişisel Verilerin Korunması Hakkında Kanun uyarınca, aşağıda detaylarını aktardığımız y&ouml;ntem ve i&ccedil;erikle, izin talep edilecektir.</p>

                <p style="text-align:justify"><strong>b. Kişisel Bilgiler :</strong>&nbsp;Metropol International, internet sitesini ziyaret eden, uygulamalarını kullanan Kullanıcıların/ziyaret&ccedil;ilerin/m&uuml;şterilerin &ouml;zel hayatlarına saygı g&ouml;sterilmesine ve kişisel verilerinin g&uuml;venliğine dikkat etmektedir. (www.Metropol International.com sitesi ve uygulamalarının tamamı kısaca &quot;Site&quot; olarak anılacaktır)<br />
                Metropol International, sizlerle ilgili elde edilen kişisel verilerin saklanmasından ve g&uuml;venliğinden sorumludur. Ayrıca, kişisel verilerinizin sizlerin onayı olmaksızın &uuml;&ccedil;&uuml;nc&uuml; kişilere iletilemeyeceğini ve sizlere bildirilen ama&ccedil;lar dışında başka ama&ccedil;larla kullanılamayacağını da belirtiriz.</p>

                <h3 style="text-align:justify">Kullanıcıların Kişisel Verilerine İlişkin Hakları</h3>

                <p style="text-align:justify">Kişisel Verilerin Korunması Kanunu&#39;nun (&ldquo;KVKK&rdquo;) 11. maddesi gereği Kullanıcılar ve &Uuml;yeler; Metropol International&rsquo;e ve/veya Metropol International tarafından a&ccedil;ıklanacak temsilciye başvurarak, kendisi ile ilgili kişisel verilerinin;<br />
                işlenip işlenmediğini &ouml;ğrenme,</p>

                <ul>
                    <li style="text-align: justify;">işlenmişse buna ilişkin bilgi talep etme,</li>
                    <li style="text-align: justify;">işlenme amacını ve bunların amacına uygun kullanılıp kullanılmadığını &ouml;ğrenme,</li>
                    <li style="text-align: justify;">yurt i&ccedil;inde veya yurt dışında aktarıldığı &uuml;&ccedil;&uuml;nc&uuml; kişileri bilme,</li>
                    <li style="text-align: justify;">eksik veya yanlış işlenmişse d&uuml;zeltilmesini isteme,</li>
                    <li style="text-align: justify;">KVKK&#39;nın 7. maddesinde &ouml;ng&ouml;r&uuml;len şartlar &ccedil;er&ccedil;evesinde silinmesini / yok edilmesini isteme,</li>
                    <li style="text-align: justify;">Yukarıda belirtilen (d) ve (e) bentleri uyarınca yapılan işlemlerin kişisel verilerin aktarıldığı &uuml;&ccedil;&uuml;nc&uuml; kişilere bildirilmesini isteme,</li>
                    <li style="text-align: justify;">işlenen verilerin m&uuml;nhasıran otomatik sistemler ile analiz edilmesi sureti ile kendisi aleyhine bir sonucun ortaya &ccedil;ıkmasına itiraz etme,</li>
                    <li style="text-align: justify;">kişisel verilerin kanuna aykırı olarak işlenmesi sebebiyle zarara uğraması h&acirc;linde zararın giderilmesini talep etme,</li>
                </ul>

                <p style="text-align:justify">haklarına sahiptir. Metropol International tarafından atanacak Veri Sorumlusu temsilcisi, yasal altyapı sağlandığında Veri Sorumluları Sicilinde ilan edilerek mevzuata uygun şekilde, www.Metropol International.com uzantılı web adresinde duyurulacaktır. Kişisel verilerinizle ilgili KVKK md. 11 uyarınca sahip olduğunuz haklarınızı kullanmak i&ccedil;in ya da kişisel verileriniz ile ilgili sorularınız kapsamında bizimle her zaman, destek@mibordro.com adresine mail g&ouml;ndererek ya da 0850 255 00 82 &nbsp;telefon numarasını aramak sureti ile irtibata ge&ccedil;ebilirsiniz.</p>

                <h3 style="text-align:justify">2. Topladığımız bilgileri nasıl kullanıyoruz?</h3>

                <p style="text-align:justify">Bizimle paylaştığınız bilgileri korumanın &ccedil;ok &ouml;nemli olduğunu biliyoruz. Bu bilgileri izinsiz erişim ve a&ccedil;ıklamadan korumaya yardımcı olmak i&ccedil;in mevzuat kapsamında uygun g&uuml;venlik tedbirlerini alıyoruz. &Ouml;rneğin, kişisel bilgilerinize mevzuat h&uuml;k&uuml;mleri dahilinde ulaşabilir, temin edebilir, kullanabilir, işleyebilir ve/veya yurt i&ccedil;ine/dışına aktarabiliriz. Ayrıca, bilgisayarlarınızdan bizim bilgisayarlarımıza g&ouml;ndermeden &ouml;nce kredi kartı numaraları ve diğer hassas bilgileri de şifreliyoruz. Kişisel bilgilerinize yetkisiz erişimi &ouml;nlemeye yardımcı olmak i&ccedil;in sunucularımızda &ouml;nleyici sistemler de kullanıyoruz.<br />
                Web sitemizi kullanırken kendinizi g&uuml;vende hissedebilirsiniz. Ancak, hi&ccedil;bir sistem tamamıyla g&uuml;venli değildir. Bilgilerinizi korumak i&ccedil;in gerekli t&uuml;m adımları atsak da daima, g&uuml;vence dışında kalma ihtimaliniz de vardır. Bu sebeple kişisel bilgilerinizi taşırken ve a&ccedil;ıklarken &ccedil;ok dikkat etmeniz gerekir. &Ouml;rneğin, e-posta ile kişisel bilgi g&ouml;ndermekten ka&ccedil;ının.<br />
                Kural olarak, kişisel verilerin ilgili kişinin a&ccedil;ık rızası olmaksızın işlenmesi m&uuml;mk&uuml;n olmamakla birlikte, &nbsp; &ldquo;bir s&ouml;zleşmenin kurulması veya ifasıyla doğrudan doğruya ilgili olması kaydıyla, s&ouml;zleşmenin taraflarına ait kişisel verilerin işlenmesinin gerekli olması&rdquo;, &ldquo; Bir hakkın tesisi, kullanılması veya korunması i&ccedil;in veri işlemenin zorunlu olması&rdquo;, &ldquo; Veri sorumlusunun hukuki y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml;n&uuml; yerine getirebilmesi i&ccedil;in zorunlu olması&rdquo;, &ldquo; ilgili kişinin kendisi tarafından alenileştirilmiş olması&rdquo;, &ldquo;İlgili kişinin temel hak ve &ouml;zg&uuml;rl&uuml;klerine zarar vermemek kaydıyla, veri sorumlusunun meşru menfaatleri i&ccedil;in veri işlenmesinin zorunlu olması&rdquo; ve/veya &ldquo;Kanunlarda a&ccedil;ık&ccedil;a &ouml;ng&ouml;r&uuml;lmesi&rdquo;durumlarından herhangi birinin mevcudiyeti halinde, ilgili kişinin a&ccedil;ık rızası aranmaksızın kişisel verilerinin işlenmesi m&uuml;mk&uuml;n olabilecektir.</p>

                <p style="text-align:justify"><strong>a. Kişisel Olmayan Bilgiler<br />
                Kişisel Olmayan Bilgiler şahsen sizi tanımlayamayacağı i&ccedil;in bu bilgileri her t&uuml;rl&uuml; ama&ccedil;la kullanabiliriz. &Ouml;rneğin, ziyaret saatlerini, sitemizde harcanan ortalama s&uuml;reyi ve incelenen sayfaları &ouml;l&ccedil;mek ve sunucularımızdaki problemleri teşhis etmek ve sitemizi y&ouml;netmek, sitemizin &ouml;zelliklerini ve fonksiyonelliğini analiz etmek ve iyileştirmek i&ccedil;in kullanabiliriz.</strong>Ayrıca, şahsen sizi tanımlamayan kişisel olmayan bu bilgileri herhangi bir ama&ccedil;la &uuml;&ccedil;&uuml;nc&uuml; kişilerle paylaşma hakkımız saklıdır. Bu bilgileri, reklam ama&ccedil;larıyla kullanılmak &uuml;zere veya topluca ya da herhangi bir Kişisel Bilginizi a&ccedil;ıklamayacak başka şekillerde Metropol International ailesinin par&ccedil;ası olmayan &uuml;&ccedil;&uuml;nc&uuml; kişilerle de paylaşabiliriz.</p>

                <p style="text-align:justify"><strong>b. Kişisel ve/veya &Ouml;zel Nitelikli Kişisel Verilere Dair A&ccedil;ık Onay:</strong>&nbsp;Internet sitemizden hizmet satın alan Metropol International m&uuml;şterileri, internet sitemizin kullanıcıları ve/veya diğer kişisel veri paylaşan kişiler, sitemizde veya &uuml;ye panelimizde yayımlanan &quot;Kişisel Verilerin Korunması Kanunu Kapsamındaki Onay Metni&quot;nin &uuml;zerine &ldquo;tik&rdquo; atmak sureti ile kişisel /veya &ouml;zel nitelikli kişisel verilerinin alınmasına, işlenmesine ve yurt i&ccedil;i/dışı aktarılmasına yasal d&uuml;zenlenmenin &ouml;ng&ouml;rd&uuml;ğ&uuml; kapsamda izin vermiş olurlar.<br />
                Kişisel veriler bakımından gerekli izinler verilmediği takdirde, Site&#39;de bazı &ouml;zelliklerin kullanım dışı kalabileceği, hizmetin kısmen veya tamamen sunulamayacağı, başka bir anlatımla hizmet satın alma işleminin yapılamayabileceği &ouml;nemle dikkate alınmalıdır. Zira, istinasi durumlar saklı kalmak kaydı ile, hizmet satın alabilmek i&ccedil;in kişisel verilerin temin edilmesinin, işlenmesinin ve aktarımının gerekli olduğu g&ouml;z ardı edilmemelidir.&nbsp;<strong>Kişisel verilerin temin edilmesine, işlenmesine ve/veya aktarıma dair gerekli onayın verilmemesi nedeni ile hizmet satışı yapılamamasından dolayı Metropol International hi&ccedil;bir sorumluluk kabul etmemekte ve Metropol International&rsquo;nin hi&ccedil;bir sorumluluğu bulunmamaktadır.</strong><br />
                .&nbsp;</p>

                <p style="text-align:justify"><strong>Kişisel Verileriniz ne şekilde işlenebilecektir?</strong><br />
                Metropol International olarak, veri sorumlusu sıfatı ile Şirketimiz ve Şirketimiz adına perakende satış kanallarımız, &ccedil;ağrı merkezlerimiz, bağlı şirketlerimiz tarafından ya da internet sitelerimiz ile sosyal medya sayfalarımız ve/veya bunlarla sınırlı olmamak &uuml;zere her t&uuml;rl&uuml; kanallar aracılığı ile; onayınız dahilinde elde edilen kişisel ve/veya &ouml;zel nitelikli kişisel verileriniz; tamamen veya kısmen elde edilebilir, kaydedilebilir, saklanabilir, depolanabilir, değiştirilebilir, g&uuml;ncellenebilir , periyodik olarak kontrol edilebilir, yeniden d&uuml;zenlenebilir, sınıflandırılabilir, işlendikleri ama&ccedil; i&ccedil;in gerekli olan ya da ilgili kanunda &ouml;ng&ouml;r&uuml;len s&uuml;re kadar muhafaza edilebilir, kanuni ya da hizmete bağlı fiili gereklilikler halinde Şirketimizin birlikte &ccedil;alıştığı &ouml;zel-t&uuml;zel kişilerle ya da kanunen y&uuml;k&uuml;ml&uuml; olduğu kamu kurum ve kuruluşlarıyla ve/veya T&uuml;rkiye&#39;de veya yurt dışında mukim olan ilgili 3. kişi ger&ccedil;ek kişi/t&uuml;zel kişilerle, sigorta şirketleri, bankalar ile paylaşılabilir/devredilebilir, kanuni ya da hizmete bağlı fiili gereklilikler halinde yurtdışına aktarılabilir ya da kullanılmasının engellenmesi de dahil olmak &uuml;zere işlenebilir. Bu meyanda, Kanun uyarınca, onayınız dahilinde Şirketimizle paylaştığınız kişisel ve/veya &ouml;zel nitelikli kişisel verilerinizin tamamen veya kısmen otomatik olan ya da herhangi bir veri kayıt sisteminin par&ccedil;ası olmak kaydıyla otomatik olmayan yollarla elde edilmesi, kaydedilmesi, depolanması, muhafaza edilmesi, değiştirilmesi, yeniden d&uuml;zenlenmesi, a&ccedil;ıklanması, aktarılması, devralınması, elde edilebilir h&acirc;le getirilmesi, sınıflandırılması ya da kullanılmasının engellenmesi gibi veriler &uuml;zerinde ger&ccedil;ekleştirilen her t&uuml;rl&uuml; işlem tarafımızdan yapılabilecektir.</p>

                <p style="text-align:justify"><strong>Kişisel verileriniz nasıl toplanmaktadır?</strong><br />
                İnternet sitemiz, satış ve pazarlama departmanı &ccedil;alışanlarımız, m&uuml;şteri ziyaretlerinde toplanan formlar, dijital pazarlama ve &ccedil;ağrı merkezi/internet sitemiz/sosyal medya/iş ortaklarımız ve bunlarla sınırlı olmamak &uuml;zere her t&uuml;rl&uuml; kanallar aracılığıyla, kişisel ve/veya &ouml;zel nitelikli kişisel verileriniz, onayınız dahilinde s&ouml;zl&uuml;, yazılı veya elektronik ortamda toplanabilmektedir. Ayrıca, internet şubesi , sosyal medya ve &ccedil;ağrı merkezi gibi kanallar aracılığıyla kişisel verileriniz s&ouml;zl&uuml;, yazılı veya elektronik ortamda toplanabilir.</p>

                <p style="text-align:justify"><strong>Kanunun Yayımından &Ouml;nceki Verilerin Durumu Nedir?</strong><br />
                Kanun h&uuml;k&uuml;mleri uyarınca, &ldquo;Bu Kanunun yayımı tarihinden &ouml;nce işlenmiş olan kişisel verileriniz, yayımı tarihinden itibaren iki yıl i&ccedil;inde bu Kanun h&uuml;k&uuml;mlerine uygun h&acirc;le getirilecektir. Buna karşın, Kanunun yayımı tarihinden &ouml;nce hukuka uygun olarak alınmış rızalar, bir yıl i&ccedil;inde aksine bir irade beyanında bulunulmaması h&acirc;linde, bu Kanuna uygun kabul edilmiş sayılmaktadır&rdquo;. Belirtiriz ki, Metropol International m&uuml;şterileri, Metropol International&rsquo;nden hizmet satın almakla Kullanım Koşullarını ve Gizlilik Politikası h&uuml;k&uuml;mlerini kabul etmiş sayıldığından ve Gizlilik Politikalarımızda, kişisel ve/veya &ouml;zel nitelikli kişisel verilerinizin teminine, işlenmesine ve aktarımına dair detaylı d&uuml;zenlemeler olduğundan, Kanun&rsquo;un yayımı tarihinden &ouml;nce temin ettiğimiz ve işlenmiş olan kişisel /veya &ouml;zel nitelikli kişisel verilerinize ilişkin olarak, tarafımıza verilen &ldquo;hukuka uygun rızanız&rdquo; bulunmaktadır. Kanuna istinaden, bu rızalarınız, bir yıl i&ccedil;inde aksine bir irade beyanında bulunulmaması h&acirc;linde, bu Kanuna uygun kabul edilmiş sayılmaktadır.</p>

                <p style="text-align:justify"><strong>Kişisel verilerinizin işlenme ama&ccedil;ları ve hukuki sebepleri nelerdir?</strong><br />
                En başta m&uuml;şterilerimizin Metropol International&rsquo;den talep ettiği hizmetleri satıp, pazarlamak ve dağıtabilmek, m&uuml;şterilerimize verdiğimiz hizmetleri s&ouml;zleşmenin ve teknolojinin gereklerine uygun şekilde yapabilmek, sizlere sunduğumuz &uuml;r&uuml;n ve hizmetlerimizi geliştirebilmek i&ccedil;in bizimle paylaştığınız kişisel ve/veya &ouml;zel nitelikli kişisel verilerinizi 6698 sayılı Kişisel Verilerin Korunması Kanunu ve ilgili mevzuata uygun olarak alıp, işleyeceğiz.<br />
                Ayrıca, en başta hizmet satışı yapabilmek ve m&uuml;şterilerimizin Metropol International&rsquo;den temin ettiği hizmeti sunabilmemiz i&ccedil;in kimlik, adres ve diğer gerekli bilgileri kaydetmek; elektronik veya kağıt ortamında işleme dayanak olacak t&uuml;m kayıt ve belgeleri d&uuml;zenlemek; mevzuat kapsamında ve yetkili otoritelerce talep edilen bilgi saklama, raporlama, bilgilendirme vb y&uuml;k&uuml;ml&uuml;l&uuml;klere riayet etmek; talep edilen &uuml;r&uuml;n / hizmetleri sunabilmek ve talep ettiğiniz hizmetin ve de s&ouml;zleşmenin gereğini yerine getirmek, i&ccedil;eriğindeki sebepler de kişisel verilerinizin işlenme ama&ccedil; ve sebeplerini oluşturmaktadır.<br />
                Kural olarak, kişisel verilerin ilgili kişinin a&ccedil;ık rızası olmaksızın işlenmesi m&uuml;mk&uuml;n olmamakla birlikte, &ldquo; bir s&ouml;zleşmenin kurulması veya ifasıyla doğrudan doğruya ilgili olması kaydıyla, s&ouml;zleşmenin taraflarına ait kişisel verilerin işlenmesinin gerekli olması&rdquo;, &ldquo; Bir hakkın tesisi, kullanılması veya korunması i&ccedil;in veri işlemenin zorunlu olması&rdquo;, &ldquo; Veri sorumlusunun hukuki y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml;n&uuml; yerine getirebilmesi i&ccedil;in zorunlu olması&rdquo;, &ldquo; ilgili kişinin kendisi tarafından alenileştirilmiş olması&rdquo;, &ldquo;İlgili kişinin temel hak ve &ouml;zg&uuml;rl&uuml;klerine zarar vermemek kaydıyla, veri sorumlusunun meşru menfaatleri i&ccedil;in veri işlenmesinin zorunlu olması&rdquo; ve/veya &ldquo;Kanunlarda a&ccedil;ık&ccedil;a &ouml;ng&ouml;r&uuml;lmesi&rdquo;durumlarından herhangi birinin mevcudiyeti halinde, ilgili kişinin a&ccedil;ık rızası aranmaksızın kişisel verilerinin işlenmesi m&uuml;mk&uuml;n olabilecektir.<br />
                Kişisel verilerinizin kullanılma ve işlenme ama&ccedil;larının detayları da aşağıda &ouml;zetlenmektedir;<br />
                <strong>i. Site:</strong>&nbsp;Bize verdiğiniz Kişisel Bilgileri, onayınız dahilinde, ilgi alanlarınıza g&ouml;re daha iyi bir site yapmak, ilgilenebileceğiniz i&ccedil;erikleri g&ouml;stermek ve i&ccedil;eriği tercihlerinize g&ouml;re ekrana getirmek i&ccedil;in kullanabiliriz.&nbsp;<br />
                <strong>ii. İletişim:</strong>&nbsp;Kişisel Bilgilerinizi, onayınız dahilinde size Metropol International ve hizmetleri ile bazı ortaklarımız adına promosyonlar hakkında bilgi vermek i&ccedil;in kullanabiliriz.&nbsp;<br />
                <strong>iii. İdari Hususlar:</strong>&nbsp;Metropol International, Site Kullanım Şartları ve/veya işbu Gizlilik Politikasında herhangi bir değişiklik olması halinde sizinle irtibata ge&ccedil;me ya da sizi sitemize ilişkin diğer idari konular (&ouml;rn. bir işlemi kolaylaştırma, tamamlamak ya da teyit etmek i&ccedil;in bağlantıya ge&ccedil;me) hakkında bilgilendirme hakkını saklı tutar.<br />
                <strong>iv. Taleplerin Yerine Getirilmesi ve İşlemlerin Kolaylaştırılması:</strong>&nbsp;Metropol International taleplerinizi yerine getirmek ve işlemlerini kolaylaştırmak i&ccedil;in onayınız dahilinde Kişisel Bilgilerinizi kullanabilir. Buna karşın,&nbsp;<br />
                mevzuat uyarınca &ldquo;&nbsp;<u>bir s&ouml;zleşmenin kurulması veya ifasıyla doğrudan doğruya ilgili olması kaydıyla, s&ouml;zleşmenin taraflarına ait kişisel verilerin işlenmesinin gerekli olması</u>&rdquo;, &ldquo; Bir hakkın tesisi, kullanılması veya korunması i&ccedil;in veri işlemenin zorunlu olması&rdquo;, &ldquo; Veri sorumlusunun hukuki y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml;n&uuml; yerine getirebilmesi i&ccedil;in zorunlu olması&rdquo;, &ldquo; ilgili kişinin kendisi tarafından alenileştirilmiş olması&rdquo;, &ldquo;İlgili kişinin temel hak ve &ouml;zg&uuml;rl&uuml;klerine zarar vermemek kaydıyla, veri sorumlusunun meşru menfaatleri i&ccedil;in veri işlenmesinin zorunlu olması&rdquo; ve/veya &ldquo;Kanunlarda a&ccedil;ık&ccedil;a &ouml;ng&ouml;r&uuml;lmesi&rdquo;&nbsp;<u><strong>durumlarından herhangi birinin mevcudiyeti halinde</strong></u><strong>, ilgili kişinin a&ccedil;ık rızası aranmaksızın kişisel verilerinin işlenmesi m&uuml;mk&uuml;n olabilecektir.&nbsp;</strong><br />
                <strong>v. &Ouml;zel İşletme Ama&ccedil;ları:</strong>&nbsp;Kişisel Bilgilerinizi, onayınız dahilinde, reklam hedeflemesi, veri analizleri, denetimler, dolandırıcılık &ouml;nleme ve diğer dahili işletme ama&ccedil;larımız i&ccedil;in de kullanabiliriz.<br />
                <strong>vi. Alışveriş/ Ticari Hizmetler:</strong>&nbsp;Site vasıtasıyla bir satın alım yaptığınızda, kredi kart numarası, fatura adresi ve bu satın alımaya ilişkin diğer bilgilerinizi (birlikte &ldquo;&Ouml;deme Bilgileri&rdquo;) onayınız dahilinde sizden alabiliriz. Satın alımınızı size faturalandırmak i&ccedil;in ve satın alma işleminizi ger&ccedil;ekleştirmek i&ccedil;in onayınız dahilinde verdiğiniz &Ouml;deme Bilgilerini kullanacağız. &Ouml;deme Bilgilerinizi vermek suretiyle, siparişinizi teyit etmek ve yerine getirmek i&ccedil;in gerektiğinde &uuml;&ccedil;&uuml;nc&uuml; şahıslara yine onayınız dahilinde ve gerektiği kadarı ile bu bilgileri vermek i&ccedil;in bize yetki vermektesiniz (&ouml;rneğin, kredi kart numaranızı işlemek).<br />
                <strong>vii. Sosyal medyada paylaşın:</strong>&nbsp;Sitemiz, onayınız dahilinde ilan edilen bazı etkinlikleri ya da site &ouml;zelliklerine linkleri e-posta ya da Sosyal Medya Servisleriyle ilgileneceğine inandığınız diğer kişilere iletmenize imkan tanır.<br />
                <strong>viii. B&uuml;lten Aboneliği:</strong>&nbsp;Sitemiz, onayınız dahilinde ilan edilen bazı etkinlikleri, promosyonları ya da hizmetlerimizin &ouml;zelliklerini anlatan metinleri ve linkleri e-posta servisleriyle size iletir.</p>

                <p style="text-align:justify"><strong>c. İş İlanları</strong><br />
                Metropol International&rsquo;e bir iş i&ccedil;in başvuru yaptığınızda ve web sitemizle kişisel bilgilerinizi yolladığınızda, işbu bilgiler sadece başvurunuzu değerlendirmek ve başvurunuzla ilgili işlemleri yapmak i&ccedil;in kullanılacaktır. Kişisel bilgilerinizi, mevcut ya da ileride mevcut olacak pozisyonlar i&ccedil;in başvurunuzu değerlendirmek amacıyla onayınız dahilinde belli bir s&uuml;re saklayabiliriz</p>

                <h3 style="text-align:justify"><strong>3. Kişisel verilerinizi aktarabileceğimiz kişi veya kuruluşlar hakkında bilgilendirme</strong></h3>

                <p style="text-align:justify">Yukarıda belirtilen ama&ccedil;larla, bizimle paylaştığınız kişisel ve/veya &ouml;zel nitelikli kişisel verilerinizin onayınız dahilinde aktarılabileceği kişi / kuruluşlar; doğrudan/dolaylı yurt i&ccedil;i/yurt dışı iştiraklerimiz; faaliyetlerimizi y&uuml;r&uuml;tmek &uuml;zere hizmet aldığımız/ iş birliği yaptığımız, program-hizmet ortağı şahıs ve kuruluşlar, Bankalar, yurti&ccedil;i / yurtdışı kuruluşlar ve diğer ilgili 3. Kişilerdir. Bu meyanda belirtiriz ki, Şirketimiz, birlikte &ccedil;alıştığı iş ortakları ile aracılıkta bulunduğundan, tarafınıza ait gerekli kişisel ve/veya &ouml;zel nitelikteki kişisel bilgileri, gereklilik kapsamında iş ortakları ile, bankalarla ve/veya talep edilen hizmetin kapsamına g&ouml;re diğer ilgili &uuml;&ccedil;&uuml;nc&uuml; kişilerle paylaşabilmekte, yurt i&ccedil;ine ve/veya yurt dışına aktarabilmektedir.</p>

                <p style="text-align:justify"><strong>a. Bağlı Ortaklık İletişimleri:</strong>&nbsp;S&ouml;zleşme kapsamındaki ticari elektronik iletiler, &ouml;nceden onaylarınız alınmak kaydıyla sizlere g&ouml;nderilebilir. Bu onayın, yazılı olarak veya her t&uuml;rl&uuml; elektronik iletişim ara&ccedil;larıyla alınabilmesi m&uuml;mk&uuml;n olduğundan, s&ouml;zleşme kapsamında ticari elektronik ileti g&ouml;nderilmesini istemez iseniz, &ldquo;elektronik ileti g&ouml;nderilmesi&rdquo; b&ouml;l&uuml;m&uuml;ndeki onay işaretini kaldırmanız gerektiğini hatırlatırız. Ayrıca, dilediğiniz zaman, hi&ccedil;bir gerek&ccedil;e belirtmeksizin ticari elektronik iletileri almayı reddedebilme hakkına da sahipsiniz. Buna karşın, kendinizle iletişime ge&ccedil;ilmesi amacıyla iletişim bilgilerini vermeniz h&acirc;linde, temin edilen hizmetlere ilişkin değişikliklere ve/veya kullanıma y&ouml;nelik ticari elektronik iletiler i&ccedil;in ayrıca onay alınmayacağını da belirtiriz.<br />
                Ayrıca, hizmetin sağlanması sırasında, bu t&uuml;r haberleşmenin yapılacağına dair sizlerin onayının alınması h&acirc;linde, yeni bir onay alınmaksızın aynı veya benzer hizmetlerle ilgili pazarlama, tanıtım ve/veya değişiklik hizmetleri i&ccedil;in haberleşme yapılabilmesi de hukuken m&uuml;mk&uuml;nd&uuml;r. Bununla birlikte, bu t&uuml;r haberleşme yapılmasını reddetme ve bu kapsamda verdiğiniz izinleri geri alma hakkınız saklıdır ve bu talebinizin tarafımıza her t&uuml;rl&uuml; yolla iletilmesi yeterlidir. &Ouml;nceden onaylı e-posta sistemine katılmayı se&ccedil;tiğiniz takdirde size, bağlı ortaklıklarımız da, ilginizi &ccedil;ekebilecek etkinlikler, &uuml;r&uuml;n ya da hizmetlerin ilan ve bildirilerini g&ouml;nderebilirler. Dilediğiniz zaman &ouml;nceden verdiğiniz onayı kaldırabileceğinizi de yineleriz. İlave bilgiler i&ccedil;in l&uuml;tfen aşağıdaki &ldquo;&Ouml;nceden Onaylı Se&ccedil;enekler Politikasına&rdquo; b&ouml;l&uuml;m&uuml;ne bakın.&nbsp;</p>

                <p style="text-align:justify"><strong>b. Metropol International Servis Sağlayıcıları:</strong>&nbsp;Veri analizi, hizmet teslimatı, kredi kart işlemleri ve idari nitelikteki diğer işler de dahil olmak, ancak bunlarla sınırlı olmamak &uuml;zere hizmet sağlayıcı olarak &uuml;&ccedil;&uuml;nc&uuml; kişilerle &ccedil;alışmaktayız. Hizmetlerimizi kullandığınız takdirde, onayınız olması durumunda, Kişisel Bilgilerinizin bu &uuml;&ccedil;&uuml;nc&uuml; kişilerle, ilgili hizmetleri sunabilmesi i&ccedil;in onayınız &ccedil;er&ccedil;evesinde ve gerektiği kadarıyla paylaşılması konusunda hakkımız saklıdır. Bu &uuml;&ccedil;&uuml;nc&uuml; kişilerin de Kişisel Bilgilerinize bizim g&ouml;sterdiğimiz &ouml;zeni g&ouml;stermeleri i&ccedil;in t&uuml;m makul adımları atmaktayız ve &uuml;&ccedil;&uuml;nc&uuml; kişiler de kişisel bilgilerinizin muhafazasından mevzuat kapsamında aynen sorumlu olacaklardır.&nbsp;</p>

                <p style="text-align:justify"><strong>c. Diğer Ama&ccedil;lar:</strong><br />
                - Bir mahkeme emri ya da benzer araştırma talebi, yetkili bir devlet kurumundan gelen işbirliği talebi; yasal haklarımızı tespit etmek ya da uygulamak; hukuki taleplere karşı savunma yapmak; ya da hukuken gereken başka durumlarda da Kişisel Bilgilerinizi paylaşabilir, herhangi bir hak ya da itirazı kullanabilir ya da bunlardan feragat edebiliriz.</p>

                <h3 style="text-align:justify"><strong>4. Bilgilerin &Uuml;&ccedil;&uuml;nc&uuml; Taraflarca Toplanması</strong></h3>

                <p style="text-align:justify"><strong>a. &Uuml;&ccedil;&uuml;nc&uuml; Kişi Reklamları</strong>: Sitemiz &uuml;zerinde g&ouml;r&uuml;nen reklamlar size &uuml;&ccedil;&uuml;nc&uuml; kişi reklam ortaklarımız tarafından sunulur. Sitemize reklam veren &uuml;&ccedil;&uuml;nc&uuml; kişiler tarayıcınız &uuml;zerine eşsiz bir &ccedil;erez koyabilir ya da bunu tanıyabilirler. Bir reklama bakma sayınız gibi site ziyaretleriniz hakkındaki Kişisel Olmayan Bilgiler size reklam servisi yapmak i&ccedil;in kullanılabilir.&nbsp;<br />
                <strong>b. &Uuml;&ccedil;&uuml;nc&uuml; Kişi Linkleri:</strong>&nbsp;Sitemiz, Metropol International tarafından sahip olunmayan ya da işletilmeyen, &uuml;&ccedil;&uuml;nc&uuml; kişilere ait web sitelerine, linkler i&ccedil;erebilir. Bu linkleri sadece rahatlık sağlamak amacıyla koyarız. Sitemiz &uuml;zerine bir linkin konulması Metropol International tarafından link verilen sitenin g&uuml;venli ve/veya onaylı olduğu anlamına gelmez.<br />
                Herhangi b&ouml;yle bir &uuml;&ccedil;&uuml;nc&uuml; kişi web sitesine Kişisel Bilgilerinizi verdiğiniz takdirde, işleminiz bu &uuml;&ccedil;&uuml;nc&uuml; tarafın web sitesince (Metropol International.com tarafından değil) ger&ccedil;ekleştirilecek ve verdiğiniz Kişisel Bilgileriniz o &uuml;&ccedil;&uuml;nc&uuml; taraf tarafından toplanacak ve onların gizlilik politikasıyla kontrol edilecektir. Bu web sitelerinin sizin onlara verdiğiniz herhangi bir Kişisel Bilgiyi kullanması dahil kendi gizlilik uygulamaları ya da bu &uuml;&ccedil;&uuml;nc&uuml; taraf web sitelerinin i&ccedil;eriğinden Metropol International sorumlu değildir. Yine, Metropol International, link verilen diğer web sitelerinin gizlilik uygulamaları veya i&ccedil;eriklerinden veya &uuml;&ccedil;&uuml;nc&uuml; kişilerin gizlilik politikaları ve uygulamalarından veya &uuml;&ccedil;&uuml;nc&uuml; kişilerin topladığı, işlediği-aktardığı ya da kullandığı &ldquo;kişisel veriler&rdquo; den sorumlu değildir.&nbsp;</p>

                <h3 style="text-align:justify"><strong>5. Onayınız Dahilindeki &Ouml;nceden Onaylı Se&ccedil;enekler Politikası</strong></h3>

                <p style="text-align:justify"><strong>a. Metropol International İletişimleri:</strong>&nbsp;Metropol International&rsquo;e Kişisel Bilgilerinizi verdiğinizde ve onayınız olduğunda, zaman zaman Metropol International&rsquo;in takdirinde olmak &uuml;zere, bizden Site, Metropol International ve/veya reklamcılarımız ve ortaklarımızla ilgili olarak &ouml;zel teklifler hakkında bilgilendirme almayla ilgilenip ilgilemediğinizi belirtmeniz istenebilir. Bu iletişimleri almak i&ccedil;in kaydolmayı se&ccedil;tiğinizde zaman zaman pazarlama iletişimleri g&ouml;nderebiliriz. Dilediğiniz zaman, bu iletişimleri almaktan tek yanlı şekilde vazge&ccedil;ebilme hakkına sahip olduğunuzu da hatırlatırız.<br />
                Herhangi bir zamanda bize e-posta atarak veya yazılı bildirimde bulunarak e-postaları almamayı se&ccedil;ebilirsiniz. Ayrıca, size, g&ouml;nderdiğimiz e-postalarda &ldquo;abonelikten &ccedil;ık&rdquo; veya &ldquo;unsubscribe this list&rdquo; diyen e-postanın altındaki link &uuml;zerine tıklamak suretiyle gelecekte bu mesajları almaktan vazge&ccedil;me hakkına da sahipsiniz. Bir kayıttan &ccedil;ıkarılma talebini yerine getirmemiz 3 iş g&uuml;n&uuml;ne kadar bir zaman alabilir.&nbsp;<br />
                Bizden etkinlik, tanıtım ve promosyon e-postalarını alma kaydından &ccedil;ıkmış olsanız bile, Metropol International&rsquo;nden satın aldığınız hizmet satın almalarına dair e-posta iletişimlerini size g&ouml;nderebiliriz. Bunlar hizmet s&uuml;recindeki durumu, hizmetin teslimatı ve sunduğumuz hizmet ile ilgili g&uuml;ncel bilgiler i&ccedil;eren m&uuml;şteri hizmetleri ile ilgili e-postalar olabilir.<br />
                E-posta iletişimleri listesinden &ccedil;ıkmanın, sadece gelecekte bizden alacağınız iletişimleri etkileyeceğini unutmayın. Bilgilerinizi siz tercihlerinizi değiştirmeden &ouml;nce ya da g&uuml;ncellemeden &ouml;nce onayınız dahilinde bir &uuml;&ccedil;&uuml;nc&uuml; kişiye g&ouml;ndermişsek, bu &uuml;&ccedil;&uuml;nc&uuml; kişiyle ilgili tercihlerinizi de ayrıca değiştirmeniz gerekebilir.<br />
                <strong>b. Bağlı Ortaklık ve &Uuml;&ccedil;&uuml;nc&uuml; Kişi İletişimleri:</strong>&nbsp;Zaman zaman Metropol International&rsquo;in takdirinde ve onayınız dahilinde, size, bağlı ortaklıklarımız ve/veya &uuml;&ccedil;&uuml;nc&uuml; kişilerin iletişim listesine kaydolma fırsatı verilebilir. Herhangi b&ouml;yle bir teklif(ler)i kabul etmeyi se&ccedil;tiğiniz takdirde, bu ama&ccedil;larla Metropol International&rsquo;e verdiğiniz t&uuml;m Kişisel Bilgilerinizi, onayınız dahilinde ve gerektiği kadarı ile bağlı ortaklıklarımız ya da bu &uuml;&ccedil;&uuml;nc&uuml; taraflarla paylaşabiliriz. Fikrinizi değiştirir ve artık Kişisel Bilgilerinizi pazarlama ama&ccedil;ları i&ccedil;in bağlı ortaklıklarımız ve/veya &uuml;&ccedil;&uuml;nc&uuml; taraflarla paylaşmak istemezseniz, yukarıdaki prosed&uuml;r&uuml; takip ederek herhangi bir zamanda gelecekteki paylaşımdan &ccedil;ıkabilirsiniz.&nbsp;</p>

                <h3 style="text-align:justify"><strong>6. Sitenin &Ccedil;ocuklar tarafından kullanımı:</strong></h3>

                <p style="text-align:justify">Site on &uuml;&ccedil; (13) yaşından k&uuml;&ccedil;&uuml;k bireylere y&ouml;nelik değildir ve bu bireylerin sitemiz vasıtasıyla Kişisel Bilgilerini vermelerini istemiyoruz. Bir ebeveyn ya da veli, &ccedil;ocuğunun bize kişisel bilgilerini ebeveyn ya da velisinin izni olmadan (&ouml;rneğin yaşını yanlış g&ouml;stererek) verdiğini fark ederse; bu veli ya da ebeveyn bize destek@Metropol International.com&lsquo;dan ulaşmalıdır. Metropol International 13 yaşın altındaki &ccedil;ocukların kişisel bilgilerini aldığını tespit ederse derhal 13 yaşından k&uuml;&ccedil;&uuml;k &ccedil;ocukların sahibi olduğuna inanılan bu bilgileri ve hesapları silecektir.&nbsp;</p>

                <h3 style="text-align:justify"><strong>7.Sizin Hakkınızda Toplanan Bilgilere Erişim, G&uuml;ncelleme ya da Bunları Silme</strong></h3>

                <p style="text-align:justify">Sitemiz ayrıca, KVKH kapsamında, sizlere, bize verdiğiniz Kişisel Bilgilerinizi silme ya da değiştirme fırsatı da verir. Bunu size sağlanan panele giriş yapıp kullanıcı bilgilerinizi değiştirmek i&ccedil;in talimatları takip ederek veya iletişim kanallarımızı kullanarak yapabilirsiniz. Bu bilgilerin veritabanlarımızda olması kaydıyla, değişiklik taleplerinize yasal h&uuml;k&uuml;mler kapsamında m&uuml;mk&uuml;n olan en kısa zamanda cevap vereceğiz.. KVKH kapsamında sahip olduğunuz diğer haklara ilişjin olarak da, işbu metnin yukarıda aktardığımız &ldquo;Kullanıcıların Kişisel Verilerine İlişkin Hakları&rdquo; b&ouml;l&uuml;m&uuml;ne tekrar bakabilirsiniz.&nbsp;</p>

                <h3 style="text-align:justify"><strong>8. Kişisel Bilgilerinizin G&uuml;venliği</strong></h3>

                <p style="text-align:justify">Metropol International, sitesi vasıtasıyla toplanan Kişisel Bilgilerin g&uuml;venliğini sağlamak ve izinsiz erişimi engellemek i&ccedil;in fiziksel, elektronik ve operasyonsal tedbirler dahil olmak &uuml;zere, mevzuat h&uuml;k&uuml;mleri kapsamında g&uuml;venlik tedbirlerini kullanır.<br />
                Metropol International kontrol&uuml; altındaki Kişisel Bilgileri korumak i&ccedil;in t&uuml;m gerekli adımları atsa da internet &uuml;zerinden t&uuml;m veri iletişimleri ya da veri depolama şekillerinin %100 g&uuml;venli olduğu garanti edilemez. Bu transferler sırasında bilgilerin yolunun kesilmesi, değiştirilmesi ya da yanlış kullanımı sonucu maruz kalacağınız herhangi bir zarar i&ccedil;in sorumluluk &uuml;stlenmemekteyiz. Sitenin g&uuml;venliğinin herhangi bir ihlali olduğuna inanmak i&ccedil;in nedeniniz olduğunda l&uuml;tfen bizimle destek@Metropol International.com&lsquo;dan temasa ge&ccedil;in.</p>

                <h3 style="text-align:justify"><strong>9. &Ccedil;evimi&ccedil;i ve &Ccedil;evrimdışı Uygulamalar</strong></h3>

                <p style="text-align:justify">Bu Gizlilik Politikasının, sitemizle bağlantılı olarak sadece &ccedil;evrimi&ccedil;i bilgi toplama ve yayılması uygulamalarına ge&ccedil;erli olduğunu ve &ccedil;evrimdışı ger&ccedil;ekleştirilen herhangi bir uygulamamız i&ccedil;in ge&ccedil;erli olmadığını unutmayın.&nbsp;</p>

                <h3 style="text-align:justify"><strong>10. Siteye İlişkin Olarak Metropol International&#39;le İrtibata Ge&ccedil;me</strong></h3>

                <p style="text-align:justify">Bu Politikaya ilişkin herhangi bir sorunuz ya da farklı bir talebiniz olduğunda, bu soruları ve/veya taleplerinizi e-maille, destek@Metropol International.com&lsquo;a g&ouml;nderebilirsiniz. E-posta iletişimlerinin mutlaka g&uuml;venli olmayabileceğini unutmayın. Bu sebeple, kredi kartı bilgilerinizi ve diğer hassas bilgileri bizimle e-posta yazışmalarınızda kullanmayın.&nbsp;</p>

                <p style="text-align:justify">&nbsp;</p>

                <p style="text-align:justify">&nbsp;</p>
            </div>
        </Modal>
    </div>
</div>

</template>